### ISSUE TITLE
[F] Double tap on "Notes" tab bring me quickly on top

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#102]
![1000042011](https://github.com/aritra-tech/Notify/assets/113377431/4c68eafa-78de-4fb6-9fcd-d08ea182c5df)

**Comment by aritra-tech** [comment]
Okay will look into it.

**Comment by githubashutoshsoni** [comment]
Hey, let me know if this is up for grabs? I'm willing to take a look into this. @aritra-tech ?

**Comment by aritra-tech** [comment]
Yeah sure @githubashutoshsoni.
All the best.

**Comment by beradeep** [comment]
Hey @serrq @aritra-tech, I looked into the issue and couldn't replicate it. It's working fine on my device.

**Comment by beradeep** [comment]
Okay I see. But then it should be mentioned in the title, and the bug label should be removed, right?

**Comment by aritra-tech** [comment]
I thought it was a bug😅. Sorry my bad @beradeep @serrq.

**Comment by aritra-tech** [comment]
Yeah, nice idea @serrq, I will add this on CONTRIBUTING.md so that other contributors can also see that.

**Comment by aritra-tech** [comment]
Okay thanks @serrq will be putting this in the CONTRIBUTING.md in the next release.

**Comment by beradeep** [comment]
Hey, I felt that double tapping on 'Notes' tab is not required. Instead we can implement single tap on 'Notes' tab inside 'NotesScreen' scrolls to top.

**Comment by githubashutoshsoni** [comment]
Okay, let me check. I think it's doable.

**Comment by beradeep** [comment]
Hey, @githubashutoshsoni, I am sorry, didn't know you were working on this.

**Comment by aritra-tech** [comment]
Hey @beradeep, I have seen that you have created a PR but @githubashutoshsoni was working on this issue.

**Comment by beradeep** [comment]
Yeah, I just realised that right now as I didn't notice him throughout the discussion in the comments.

> Hey @beradeep, I have seen that you have created a PR but @githubashutoshsoni was working on this issue.

**Comment by githubashutoshsoni** [comment]
Yes, please go through the assignee section on the issues page when working. @beradeep

**Comment by githubashutoshsoni** [comment]
@aritra-tech this is done now. can you please accept my pull request.

**Comment by aritra-tech** [comment]
> @aritra-tech this is done now. can you please accept my pull request.

Yeah, I've seen it will be checking the PR soon.
