### ISSUE TITLE
[F] Multi database management

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#112]
My idea is to switch quickly among different backups (databases) in order to have various (separate) environments.

For example a database for university, work, personal stuff.

Also useful if one wants share a whole backup with strangers (for example a website) or coworkers.
In this way yon can be sure that only sharable notes are shared, because compartmentalized.

**Comment by aritra-tech** [comment]
Nice idea @serrq, need to do some research and then start the development

**Comment by aritra-tech** [comment]
Yeah, it will be difficult but can be a unique feature if we can successfully do it.
Need to do some research first
