### ISSUE TITLE
Estimated reading/listening time, file weight and other useful info

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#116]
I very appreciated the words counter. But newspaper articles are always separated in long-term (about 25 minutes of reading) and short-term, less than 25 minutes.

Another useful info is file dimension within the reading view, as seen for words counter.

What do you think if Notify has these features?

Example:

📦 Markdown

📄 245 words

💾  12.3 kb 

⏱️ 6 minutes

PS: also useful for voice notes.
Of course voice note will not have the words counter field.

I added the file type field too.
All these informations provide an overall sight about the memo with which I have to treat to.

**Comment by aritra-tech** [comment]
Can get your point clearly can you send me an example where you have seen like this.

**Comment by aritra-tech** [comment]
Okay will look into it.

**Comment by Ismail-AD** [comment]
@aritra-tech i think so that will change the Note Schema as well (new attributes will be required for Note Model) can i deal with this If so I have one more question as well !!!

**Comment by aritra-tech** [comment]
Yeah sure you can @Ismail-AD.
