### ISSUE TITLE
Self-cleaning 28 days trash bin (optional)

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#117]
It would be useful a trash bin that hold all the deleted notes and permanently delete them after 4 weeks (if not restored).

**Comment by aritra-tech** [comment]
Nice idea, will try to work on this idea.

**Comment by salmanA169** [comment]
let me try on this @aritra-tech

**Comment by aritra-tech** [comment]
Hey @salmanA169 just wanted to know where will you place the trash bin functionality.

**Comment by salmanA169** [comment]
1- When long click in note it shows dialog for confirm to move to trash
2- create new table for TrashNote (noteId :Int , dateTimeDeleted:Long)
3- when move note to Trash delete note from NoteTable and after 28 day it will delete auto there is two way to implement it
first when user open app it check TrashNote Table if not empty and check from deleted dateTime if => 28 day delete it 
second using work manager for schedule every 6 hours to check TrashNote
- Also you can restore trash note feat

**Comment by salmanA169** [comment]
@aritra-tech

**Comment by aritra-tech** [comment]
Got your point but I was telling you where you will place the trash in the app. If you have seen Keep Notes then you will notice that there is a dedicated `Deleted` section on their app from where the user can restore the notes.
So in Notify, I was thinking of putting that trash section on Settings under `App Settings`.
I hope you got it @salmanA169.

**Comment by salmanA169** [comment]
Ok I will start now 
do it on new branch or where ?

**Comment by aritra-tech** [comment]
Yeah new branch and create your new branch from `develop`

**Comment by salmanA169** [comment]
for now I almost finish it just need improve UI and implement auto delete after 28 day and also restore fun 
I will continue tomorrow because I have work 


https://github.com/aritra-tech/Notify/assets/40442174/55cbcaae-38f1-4efd-ae35-786e492da374

**Comment by aritra-tech** [comment]
> for now I almost finish it just need improve UI and implement auto delete after 28 day and also restore fun 
> I will continue tomorrow because I have work 
> 
> 
> https://github.com/aritra-tech/Notify/assets/40442174/55cbcaae-38f1-4efd-ae35-786e492da374
> 
> 

Nice work @salmanA169 .
Just a suggestion to put the trash option below the Dark Mode.

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/265b79dd-8737-40fe-82a1-06793d1b9b85



sorry for late 
last 3 days I was so busy
now I app delete trash note after 28 days
now I will implement for restore fun and Improve trash note screen 
@aritra-tech

**Comment by aritra-tech** [comment]
No issues @salmanA169 take your time.
By the way nice work 🙌.

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/4a08a38d-df13-4699-8f01-7854f30aabfc



I think I done this issue
**Also I fixed issue when edit note it always save empty data when save edited note** 
@aritra-tech

**Comment by salmanA169** [comment]
I will create PR

**Comment by salmanA169** [comment]
how create PR
 The requested URL returned error: 403
No permission

**Comment by aritra-tech** [comment]
> how create PR The requested URL returned error: 403 No permission

Can't get your point

**Comment by salmanA169** [comment]
I can not create pull request

**Comment by aritra-tech** [comment]
Checkout any video regarding how to create PR on yt.

**Comment by salmanA169** [comment]
#151 PR 
@aritra-tech

**Comment by aritra-tech** [comment]
There is an issue regarding your PR @salmanA169.
I have reverted back the changes that you have made.
#151 check the comment that I have added.

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/97afd245-839e-4527-b07d-d557b0ee375d




Fix it 
It was simple mistake when I resolve conflict I remove last curly bracket 
Now create new PR ?

**Comment by aritra-tech** [comment]
Why the date and time is showing twice in the `AddEdit Screen`
I should only show `15 Oct 11:42 PM | 6 sec read`

**Comment by aritra-tech** [comment]
Now in the develop it's showing one only.

**Comment by aritra-tech** [comment]
Check if your branch is updated with develop.
Ig something is missing.

**Comment by salmanA169** [comment]
I run app on base develop branch it show two date 
I told you you merge from this commit check it 
https://github.com/aritra-tech/Notify/commit/7c295f45f37cb9f8ea5cb8d6aa061c22c441579d

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/90398001-c53d-44dc-aa5c-2c58193fae31

I fixed it 
now I will create new PR and check it

**Comment by salmanA169** [comment]
#158

**Comment by salmanA169** [comment]
Yes each note has its own count time
**also I will update on end corner I will add text to show Shows the number of days remaining**
