### ISSUE TITLE
Notes sorting modes

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#118]
Currently my notes are showed upsidedown.
The old notes are on top. The new ones on bottom.

Might you give me more power on notes sorting?

**Comment by aritra-tech** [comment]
Got your point.
Noted down.

**Comment by V9vek** [comment]
Hi @aritra-tech, I would like to work on this, if this is open for contribution, please assign it to me 🤩

**Comment by aritra-tech** [comment]
Yeah sure @V9vek.
All the best 
Please read the [CONTRIBUTING.md](https://github.com/aritra-tech/Notify/blob/master/CONTRIBUTING.md).

**Comment by V9vek** [comment]
@aritra-tech I want to ask whether we should just sort the notes on basis of at what date/time the note was added, and the latest note will be on top
or we should have more options like sort on basis of the Title (ascending / descending) ?
The latter will need some more UI like we need to open a dialog or kind of bottomsheet to get input from user.

For now I will create a PR for just getting latest notes on top.

**Comment by V9vek** [comment]
@serrq But i guess there are not much options, like 
1. DateTime 
2. Title
these two are the only options I can think of rn.
Can you tell me more of such options or else I will create PR of latest note on top only for now

**Comment by aritra-tech** [comment]
Hey @V9vek as of now just do two things.
- Whenever the user adds a note it will appear at the top of the list 
- Short notes according to Date and Time

In the future we will think more about shorting.

**Comment by V9vek** [comment]
can you give me a basic skeleton UI (screenshot from excalidraw or anything) like how it should be look.
It would be more helpful 🙏🏻

**Comment by aritra-tech** [comment]
> can you give me a basic skeleton UI (screenshot from excalidraw or anything) like how it should be look. It would be more helpful 🙏🏻

In the search bar only gives a filter icon, clicking it will open up a dialog with the sorting thing & there will be radio buttons for every sorting option.
I hope you got it.

**Comment by aritra-tech** [comment]
> I hope in future you build an amazing tags management system, so that searching a note among two thousands ones will be easier and faster.

Yeah I have planned for this will be doing this in the upcoming updates.

**Comment by salmanA169** [comment]
Hi 
How are you 
@aritra-tech 
I wanna contribute
let me try for this task

**Comment by aritra-tech** [comment]
Hey @salmanA169 sorry but @V9vek is already assigned & he is also working on this issue.
If you want you can explore other issues.

**Comment by V9vek** [comment]
@aritra-tech @serrq **How is this looking?** Sorting feature is working good.
I am not able to come up with some very good UI (I think its decent), but the code quality is super good.
If you want any changes, do let me know ☺

https://github.com/aritra-tech/Notify/assets/40730402/d691328c-1054-414b-a492-cf727a69a433

**Comment by V9vek** [comment]
@serrq actually when we create a note, it has only a field **date time**
So, while modifying, I guess same field is changing, so we **can not differentiate between creation and modification**  
Notes model is made in this way only. So yeah..

**Comment by V9vek** [comment]
I will create a PR for this.

**Comment by aritra-tech** [comment]
> @aritra-tech @serrq **How is this looking?** Sorting feature is working good.
> I am not able to come up with some very good UI (I think its decent), but the code quality is super good.
> If you want any changes, do let me know ☺
> 
> https://github.com/aritra-tech/Notify/assets/40730402/d691328c-1054-414b-a492-cf727a69a433
> 
> 

Nice work @V9vek.
Will check the code once and then I will merge it

**Comment by aritra-tech** [comment]
> I will create a PR for this.

Sure

**Comment by V9vek** [comment]
> > I will create a PR for this.
> 
> Sure

I have opened the PR. Do check it out.

**Comment by V9vek** [comment]
@aritra-tech do check the new PR. I was having some branch issues with my previous PR, so I have created a brand new PR for the same.

**Comment by aritra-tech** [comment]
> @aritra-tech do check the new PR. I was having some branch issues with my previous PR, so I have created a brand new PR for this same issue.

Okay I will have a look into the code and merge it asap
