### ISSUE TITLE
Impossible managing the notifications' permission

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#121]
Maybe a bug. 

![1000042105](https://github.com/aritra-tech/Notify/assets/113377431/d83b4430-801d-4a73-9799-7b9a5cfb1e7a)

![1000042107](https://github.com/aritra-tech/Notify/assets/113377431/c95e202c-95f3-4ae6-bfe6-82585f82b8f0)

**Comment by aritra-tech** [comment]
As of now, there is no functionality where we need to send notifications.
So that's why it is denied.

**Comment by aritra-tech** [comment]
Hey @serrq can you please write on the discussion if you have any doubts or requested feature.
I hope you get it.
