### ISSUE TITLE
Upload Notify to F-Droid

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#125]
Wanted to upload Notify to F-Droid

**Comment by javaman97** [comment]
@aritra-tech I would love to work on this issue,would you please assign me this issue ?

**Comment by githubashutoshsoni** [comment]
Hey, Can I take this up?

**Comment by aritra-tech** [comment]
Sure @githubashutoshsoni

**Comment by aritra-tech** [comment]
Hey @githubashutoshsoni any update?
