### ISSUE TITLE
Feat : TODO list

### ISSUE THREAD

**Issue by bhoomi0104** [aritra-tech/Notify#127]
There will be option to add todo list (checkboxes) in the notes.

**Comment by aritra-tech** [comment]
Yeah, nice idea.
Can do it.

**Comment by bhoomi0104** [comment]
Thanks

**Comment by dustinhartlyn** [comment]
Search feature seemed to only searches the note titles for me. I most often I am looking for a text in the body of a note. Not sure how hard it is to implement this.

**Comment by aritra-tech** [comment]
Hey @dustinhartlyn most users search using their title only because it's short and easy to remember that's why I have only added search using title functionality.
I hope you got it.

**Comment by aritra-tech** [comment]
Hey @bhoomi0104 any update?

**Comment by logickoder** [comment]
@aritra-tech would like to work on this to
