### ISSUE TITLE
Bug: Text in notes description appears black in Dark Mode

### ISSUE THREAD

**Issue by beradeep** [aritra-tech/Notify#130]
## Bug description
In the `AddEditScreen`, the text inside the `DescriptionTextField` appears black even in Dark Mode.
## Expected behavior
The text should invert color to appear white in Dark Mode.

<img src="https://github.com/aritra-tech/Notify/assets/124783808/081e059f-f9b5-4b58-8b3d-30657cf63646" width="300" />

Device: Samsung Galaxy F12

**Comment by aritra-tech** [comment]
Yeah right just saw it.
Thanks for noticing @beradeep.
