### ISSUE TITLE
Removing depricated libraries

### ISSUE THREAD

**Issue by AdityaKumdale** [aritra-tech/Notify#144]
As stated [https://google.github.io/accompanist/systemuicontroller/], Accompanist System UI Controller library is deprecated.

**Comment by AdityaKumdale** [comment]
Hello I would like to contribute to this issue. Please mark it as hacktoberfest.

**Comment by aritra-tech** [comment]
> As stated [https://google.github.io/accompanist/systemuicontroller/], Accompanist System UI Controller library is deprecated.

Ohh yeah right.
Thanks for pointing it out @AdityaKumdale

**Comment by AdityaKumdale** [comment]
Hey @aritra-tech please check the pr.

**Comment by AdityaKumdale** [comment]
Hey @aritra-tech please check the pr I solved the issue.
