### ISSUE TITLE
Fix the UX of SearchBar & Bottom Nav Bar

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#148]
So, right now when we scroll the nav bar and search bar it sticks to their point but for the betterment of UX, we can do that when we scroll down the column both the nav & search bar gets hidden, and when the user scrolls up it both the nav & search bar should show up.

**Comment by salmanA169** [comment]
I can do that

**Comment by aritra-tech** [comment]
Yeah sure
I hope you got the point.

**Comment by salmanA169** [comment]
but tell me I don't have enough exp about github 
now wait to merge for my PR for cleaning note 
or start this task with current develop branch 
sorry for that

**Comment by aritra-tech** [comment]
Yeah right now start this task with creating a new branch.
Later you have to merge the updates onto your own branch.

**Comment by dharamveer-gupta** [comment]
Hi @aritra-tech, 
I have completed the enhancement #148 and created a PR for it, can you please review it.

**Comment by aritra-tech** [comment]
Hey @dharamveer-gupta thanks for contributing but this issue is already assigned to @salmanA169.
If he doesn't want to do then it will be passed to you.
I'm not closing your PR but if @salmanA169 doesn't want to work on this then I will assign it to you and merge your PR.
I hope you got it
Thank you @dharamveer-gupta.

**Comment by salmanA169** [comment]
no problem if his PR works fine assign to him 
because I am still fix my last issue for cleaning note

**Comment by aritra-tech** [comment]
> no problem if his PR works fine assign to him because I am still fix my last issue for cleaning note

Okay then @salmanA169 I'm assigning this PR him.
Thank you.
