### ISSUE TITLE
Fix the BottomAppBar color

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#159]
![WhatsApp Image 2023-10-17 at 13 06 09_bc27535e](https://github.com/aritra-tech/Notify/assets/80090908/13971363-2faf-49b5-92e4-04cf1f5a26a9)

As you can see the color of `BottomAppBar` is different from the above color.
I want the same color both in the `Column` & `BottomAppBar`.

**Comment by ayushsingh01042003** [comment]
Hey could you assign this to me?

**Comment by aritra-tech** [comment]
Sure @ayushsingh01042003.
All the best

**Comment by salmanA169** [comment]
I know fix it

**Comment by salmanA169** [comment]
only do this
` BottomAppBar(containerColor = Color.Transparent,content = {
                    IconButton(onClick = { showSheet = true }) {
                        Icon(
                            modifier = Modifier.size(25.dp),
                            painter = painterResource(id = R.drawable.add_box_icon),
                            contentDescription = stringResource(R.string.add_box)
                        )
                    }`

on container color on bottomAppBar = Color.Transpart

**Comment by salmanA169** [comment]
![Screenshot_20231019_232846](https://github.com/aritra-tech/Notify/assets/40442174/06ca7454-bfba-4a1c-89c4-675f6cda1ff4)

**Comment by salmanA169** [comment]
@ayushsingh01042003 fix it on addEditScreen

**Comment by ayushsingh01042003** [comment]
> @ayushsingh01042003 are you still working on this issue?

Yes i fixed it and will send a pr now
Thanks for the help @salmanA169 !
