### ISSUE TITLE
 Clickable Animation Issues in Bottom Navigation Item

### ISSUE THREAD

**Issue by Amit-guha** [aritra-tech/Notify#161]
When you repeatedly click on the Bottom Navigation Item (Settings), the enter and exit animations are executed repeatedly.

[Bottom_Navbar_issue.webm](https://github.com/aritra-tech/Notify/assets/54904545/ae26429a-a86b-4808-814a-a7320aff8c7d)

**Comment by Amit-guha** [comment]
I am interested to solve this issue. If you approved this issue, can you please assign me for solving the issue?

**Comment by aritra-tech** [comment]
Thanks for pointing it out.

**Comment by Amit-guha** [comment]
Thanks

**Comment by Amit-guha** [comment]
> just remove re click on current screen

Thank you for your suggestion

**Comment by Amit-guha** [comment]
@aritra-tech I sent you a pull request. Please have a look into my code.

**Comment by Amit-guha** [comment]
@aritra-tech 
The problem i faced earlier, i solved this issue a few minutes ago.  The workflow need some approval from you.I commit my changes code and push the code to my branch.Can you please Check that code?

<img width="1370" alt="incompatible_issue" src="https://github.com/aritra-tech/Notify/assets/54904545/cb1a5221-f4f0-44a2-a695-e9d0d31b1998">
