### ISSUE TITLE
Clicking the right-side navigation button should trigger a slide animation from the right side.

### ISSUE THREAD

**Issue by utkarshxf** [aritra-tech/Notify#164]
**Describe the bug**

https://github.com/aritra-tech/Notify/assets/78771861/5e732020-74fa-47f8-865b-3f01895d9680

When transitioning from the right side to the left side, the animation should follow the same right-to-left direction.

**Comment by utkarshxf** [comment]
can u assign me to fix this?

**Comment by utkarshxf** [comment]
Doesn't this issue need to be fixed?

**Comment by aritra-tech** [comment]
Sorry from my side but why did you solved issue no #161, it's already being assigned to someone else.

**Comment by aritra-tech** [comment]
Sorry @utkarshxf but I have to revert back the changes that you have made regarding that PR because that issue is already assigned to somebody else.
I was doing my office work so could not concentrate at all and merge the PR.
Sorry from my side as well.

**Comment by utkarshxf** [comment]
it's totally fine.
