### ISSUE TITLE
Making the TextEdit Section Focused on Opening AddEditScreen

### ISSUE THREAD

**Issue by Kayvee08** [aritra-tech/Notify#171]
Making the notes TextEdit Focused as soon as AddEditScreen is opened, like default behaviour.

For example as soon as we open the AddEditScreen it should look like this.
![Screenshot_20231018_234522](https://github.com/aritra-tech/Notify/assets/51030284/8548841a-e566-4524-89ff-8427ed984a2e)

**Comment by Kayvee08** [comment]
> With rise up keyboard you mean?

Yes
Something like this 

https://github.com/aritra-tech/Notify/assets/51030284/d46e1878-affe-4369-9f73-99003476080b

**Comment by Kayvee08** [comment]
If you approve this issue, can you please assign it to me.

**Comment by aritra-tech** [comment]
Should we pop up the keyboard when the cursor is at `Title` TextField or `Notes` one?

**Comment by Kayvee08** [comment]
> Should we pop up the keyboard when the cursor is at `Title` TextField or `Notes` one?

My suggestion would be to pop  up the keyboard with cursor at Notes.

**Comment by aritra-tech** [comment]
Okay, go ahead.

**Comment by MJJacobs01** [comment]
Assign the issue to me please?
