### ISSUE TITLE
Cleaning self 28 day - Add text on corner to know remaining days

### ISSUE THREAD

**Issue by salmanA169** [aritra-tech/Notify#176]
**Describe your suggested feature **
I would like to add text on bottom end note card that show when the note delete

**Comment by salmanA169** [comment]
@aritra-tech what do you think

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/5ee59815-2e2c-4a9a-a007-3da6eb73ebe8

what do you think ? @aritra-tech

**Comment by salmanA169** [comment]
no
Each note has a date on when it was deleted
Only notes  that are 28 days old will be automatically deleted

**Comment by aritra-tech** [comment]
Nice work @salmanA169.
Keep going 🚀

**Comment by aritra-tech** [comment]
Create a PR if you have completed

**Comment by salmanA169** [comment]
#179
