### ISSUE TITLE
Removing google-service.json

### ISSUE THREAD

**Issue by Krish-Parekh** [aritra-tech/Notify#180]
**Describe the bug**
Instead of including the `google-service.json`  file in the codebase, we can remove it and add instructions for installing it in the installation guide.

**Comment by aritra-tech** [comment]
Yeah google-service.json file is not needed at all. If you want you can remove i completely.

**Comment by Krish-Parekh** [comment]
Okay, so do I need to add this in CONTRIBUTING.md ?

**Comment by aritra-tech** [comment]
> Okay, so do I need to add this in CONTRIBUTING.md ?

No no not needed
