### ISSUE TITLE
Save Empty Notes

### ISSUE THREAD

**Issue by Ismail-AD** [aritra-tech/Notify#182]
**About bug**
the thing is if user give space to title and description as well he/she can save an empty note I want to fix it **Assign** to me 
@aritra-tech

**Comment by aritra-tech** [comment]
Yeah, this point has been pointed out earlier by a user but I forgot to do that.
Thanks for pointing it out once again.

**Comment by VibhorGits** [comment]
Can anyone explain me the issue?

**Comment by logickoder** [comment]
@aritra-tech if this is not currently worked on, I can handle it

**Comment by aritra-tech** [comment]
Hey @logickoder, sorry but @Ismail-AD has already created the PR.
I requested him some changes if he would able to do it within 1 or 2 days then it's ok otherwise I will assign this issue to you.

**Comment by aritra-tech** [comment]
Hey @logickoder do you want to work on it?

**Comment by logickoder** [comment]
Sure

**Comment by aritra-tech** [comment]
So the issue is that now you can see that user have to give a title and description to save their notes so I was thinking of why not save the notes when only description is given and title is blank then also we can save the note.
