### ISSUE TITLE
Adding support for pinning notes or adding favorites

### ISSUE THREAD

**Issue by Kayvee08** [aritra-tech/Notify#186]
Users can either pin notes that the deem important to the top or make then favorites which will also show those notes at the top.

**Comment by aritra-tech** [comment]
Pin sounds better @Kayvee08

**Comment by Kayvee08** [comment]
So should we add option to pin (important) notes ?

**Comment by aritra-tech** [comment]
![WhatsApp Image 2023-10-23 at 00 49 40_cbc549e0](https://github.com/aritra-tech/Notify/assets/80090908/81e4fefe-3398-4034-a93a-d0317be8adcc)

I was thinking like this now on a long click there is a feature `multi-delete option` so I was thinking that when the user long clicks then a bottom sheet opens up with two features `Delete` & `Pin` as shown in the picture.

Is the ideas feasible @Kayvee08 @serrq ?

**Comment by aritra-tech** [comment]
> What is the milestone for this feature? 1.6.0?

It will be 1.7.1 ig

**Comment by Kayvee08** [comment]
@aritra-tech currently we are showing the delete option in the top bar, so you are suggesting we move the option to pin and delete to the bottom bar right ?

**Comment by aritra-tech** [comment]
> @aritra-tech currently we are showing the delete option in the top bar, so you are suggesting we move the option to pin and delete to the bottom bar right ?

Yeah right.
What do you think is this idea good or you can tell what you want to do

**Comment by Kayvee08** [comment]
@aritra-tech bottomsheet is a good idea, but will see how others are incorporating this feature in terms of accessibility and UI.

**Comment by aritra-tech** [comment]
Hey @serrq is the idea good to go that I have shared.

**Comment by aritra-tech** [comment]
> ![WhatsApp Image 2023-10-23 at 00 49 40_cbc549e0](https://user-images.githubusercontent.com/80090908/277187546-81e4fefe-3398-4034-a93a-d0317be8adcc.jpg)
> 
> I was thinking like this now on a long click there is a feature `multi-delete option` so I was thinking that when the user long clicks then a bottom sheet opens up with two features `Delete` & `Pin` as shown in the picture.
> 
> Is the ideas feasible @Kayvee08 @serrq ?

This idea that I have told is okay for you? @serrq

**Comment by aritra-tech** [comment]
Hey @Kayvee08 then that's the final idea lets work on it.
All the best

**Comment by Kayvee08** [comment]
Okay, will start working on it @aritra-tech

**Comment by purushyb** [comment]
is anybody looking into this ??, (Since #214 is not merged yet)

**Comment by aritra-tech** [comment]
No @purushyb if you want you can pick it up

**Comment by andy-ife** [comment]
Hi @aritra-tech Can I look into this as well? Seems no one has provided an acceptable solution yet.

**Comment by aritra-tech** [comment]
yeah please @andy-ife

**Comment by andy-ife** [comment]
Alright. Will keep you posted. Hoping to get my first gh contribution lol

**Comment by andy-ife** [comment]
Hmm. What do you say @aritra-tech

**Comment by aritra-tech** [comment]
Hey @MianMuzammil67 sorry but @andy-ife is working on it 
@andy-ife please continue

**Comment by andy-ife** [comment]
> > ![WhatsApp Image 2023-10-23 at 00 49 40_cbc549e0](https://user-images.githubusercontent.com/80090908/277187546-81e4fefe-3398-4034-a93a-d0317be8adcc.jpg)
> > I was thinking like this now on a long click there is a feature `multi-delete option` so I was thinking that when the user long clicks then a bottom sheet opens up with two features `Delete` & `Pin` as shown in the picture.
> > Is the ideas feasible @Kayvee08 @serrq ?
> 
> This idea that I have told is okay for you? @serrq

@aritra-tech I'll go with this implementation if that's alright

**Comment by andy-ife** [comment]
All done @aritra-tech . Pull request #540

**Comment by aritra-tech** [comment]
I will look into the changes and merge the PR @andy-ife 
Thank you
