### ISSUE TITLE
There is issue when move note to trash it throw exception 

### ISSUE THREAD

**Issue by salmanA169** [aritra-tech/Notify#216]
**Describe the bug**
There is issue when move note to trash it throw exception

**Comment by aritra-tech** [comment]
Can you send me the exception that you are getting

**Comment by salmanA169** [comment]
let me update project then I will tell you

**Comment by salmanA169** [comment]
![Uploading Captu1re.JPG…]()

**Comment by salmanA169** [comment]
![Captu1re](https://github.com/aritra-tech/Notify/assets/40442174/1dc22bb3-14ca-4ac3-9fb7-c8a3dca84fea)
