### ISSUE TITLE
Create New Note Issue

### ISSUE THREAD

**Issue by Amit-guha** [aritra-tech/Notify#220]
If you give first character as empty space for Title and  first character as empty space for Description, it's create a new note. That means you can create a note with empty title and description. Can you Please assign me for this issue?

[Screen_recording_20231030_233047.webm](https://github.com/aritra-tech/Notify/assets/54904545/76f20939-fb90-43f6-ab9b-31ea8ea189f4)

**Comment by aritra-tech** [comment]
Yeah sure.
All the best

**Comment by Amit-guha** [comment]
I sent you a pull request.
