### ISSUE TITLE
Implement Canvas for drawing objects

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#42]

**Comment by HimanshuC22** [comment]
can you clarify if there should be a canvas above/below the text area, or a button to replace text area with canvas area?

**Comment by aritra-tech** [comment]
So there is a bottom sheet in the `AddEdit` Screen so there will be an option of `Drawing` on clicking it will open up a Canvas where the user will draw anything and on saving it will be displayed on the `AddEdit` Screen.
We also have to save it on Room DB.
I hope you got it.

**Comment by logickoder** [comment]
@aritra-tech assign this to me

**Comment by aritra-tech** [comment]
Yeah sure
All the best
