### ISSUE TITLE
Adding app shortcuts

### ISSUE THREAD

**Issue by tuuhin** [aritra-tech/Notify#446]
Adding few app shortcuts to directly allowing the user to create a note

**Comment by aritra-tech** [comment]
Good idea @tuuhin will look into it

**Comment by tuuhin** [comment]
Should I work on it..?

**Comment by aritra-tech** [comment]
Yeah sure @tuuhin.
All the best 🚀

**Comment by tuuhin** [comment]
A bit busy this week I will start it next week .

**Comment by aritra-tech** [comment]
> A bit busy this week I will start it next week .

No issues.
All the best for the exam
