### ISSUE TITLE
Fix the data backup/restore feature

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#45]
Change the data backup & restore feature and implement a feature that allows the user to backup & restore their data in the form of CSV.

**Comment by logickoder** [comment]
Is this being worked on?

**Comment by aritra-tech** [comment]
Nope @logickoder, if you want you can start working on it.

**Comment by logickoder** [comment]
Can I be assigned please

**Comment by aritra-tech** [comment]
Yeah sure

**Comment by aritra-tech** [comment]
Create your branch through **master**.

**Comment by logickoder** [comment]
Should I entirely replace the backup/restore with CSV format or should it be an option for the user?

**Comment by aritra-tech** [comment]
Entirely replace with backup/restore with CSV

**Comment by logickoder** [comment]
Okay, makes sense
