### ISSUE TITLE
Implement In-app Update feature

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#46]
Reference link for In-App update : https://developer.android.com/guide/playcore/in-app-updates/kotlin-java

**Comment by devedroy** [comment]
Hey @aritra-tech , I would like to work on this feature.
Can you please assign this issue to me?

**Comment by aritra-tech** [comment]
Hey @devedroy any update?

**Comment by aritra-tech** [comment]
Sorry @devedroy, I'm unassigning this issue it's almost 1 week but there has been no update till now.
Thank you.
