### ISSUE TITLE
signing key issue

### ISSUE THREAD

**Issue by IzzySoft** [aritra-tech/Notify#53]
There's still no answer from you on the signing key issue, you even deleted #36 where I asked what happened. So I must assume a security issue here which is attempted to be "covered" and will have to disable updates entirely for your app in my F-Droid repo, adding a warning to the description.

As the latest release also adds proprietary components (FCM), and it doesn't look as if you're interested in solving the issue above but rather hide the problem, I think the proper solution on my end is rather removing your app here entirely – which I will do now. If security issues are ignored and even hidden, I must consider that as too dangerous a source to be suggested to folks for usage, sorry.

**Comment by aritra-tech** [comment]
can we have the conversation on mail this is my mail id aritrarick2002@gmail.com

**Comment by IzzySoft** [comment]
Gmail does not accept my mails (and I don't want them to scan them anyway) as I had to find out recently, it rather "eats them silently" (they neither get delivered nor bounced), so that won't work. If you have a non-Gmail account, I gladly continue the discussion by mail (unfortunately, Github has no such thing as "confidential issues" it seems – or I haven't yet found it). You can find my mail address on the "imprint" of my servers – or just use the first 4 letters of my nick here in front of the `@`, followed by the full nick and a trailing `.de`.

**Comment by aritra-tech** [comment]
I have sent you the mail.

**Comment by IzzySoft** [comment]
I told you that Gmail seems to silently drop mails I send there? In a test run a couple of days ago, out of 4 mails, 4 failed. So sorry if my answers won't make it through – I can never tell (sometimes they do), so I cannot rely on that. Hence I'll have to continue here as this is the only means of contacting you left to me:

```
# v1.0
Signer #1 certificate DN: C=91, L=Kolkata, CN=Aritra Das
Signer #1 certificate SHA-256 digest: e73b826b3b2946f0e66c456d6c3007e236b82efa258b55dc865a3747d1271f4c
Signer #1 certificate SHA-1 digest: 3771d1e3883c4b02f43fc1d39230f55774fbdcc7
Signer #1 certificate MD5 digest: 7aec106ddc6902c7e5c640b37905bed9

# v1.1.0+
Signer #1 certificate DN: C=91, ST=West Bengal, L=Kolkata, CN=Aritra Das
Signer #1 certificate SHA-256 digest: 6b998202ca7ca7bf6376a70749c1cae6e07a2f34915eae9aea4fcd03c3c34555
Signer #1 certificate SHA-1 digest: d2cb4c287620894597f87efcd41c2330f5a37e25
Signer #1 certificate MD5 digest: dd8eba2a6b32170de31903de9fd03e6a
```

So something must have happened between v1.0 and v1.1.0. Moved to a new machine? Fresh setup? Different build environment?

It's nothing to be ashamed of, things happen. You won't believe how many developers "lose" their signing keys one way or the other (hint: since I've established the security measure of having signatures checked in my repo, there was not a single week with not at least one such occurrence – which statistically makes it look like 1 out of 20 has this issue at least once). Thing is we now need a way to keep up trust – to make sure it's really you, and that not someone else e.g. "hacked your account".

Ah, there: Good thing you're using "signed commits" from time to time! So I found several of them dating back to before the release of v1.0, and their key ID (`4AEE18F83AFDEB23`) matches what was used by the most recent signed commit long after the "incident". So, trust established: as it's pretty unlikely someone got hold of your PGP/GPG key **AND** your Github account (but not of your signing key), I'm now convinced to talk to the "original author" here.

OK, so even if what exactly happened might remain a mystery (my guess is you changed something in your development environment, which did not take along your key and thus the "convenience of the framework" kicked in generating a new key without you noticing the fact), based on the proof given by your signed commits I feel confident enough to re-establish your app – with the new key. Which I have done now, it will become [available here](https://apt.izzysoft.de/packages/com.aritra.notify/) with the next sync at around 6 pm UTC again. That said, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to point there, accompanying the two (Google, Github) already present in your Readme :wink:

Sorry for the inconvenience, but I had to make sure all is "in order" (your deleting that other issue without any proper note was just looking … ahem … "strange"). And thanks for understanding! Should you find out what lead to the key change, please let me know: I'm collecting how things can go wrong with that for a possible write-up (of course without naming people) including how to best prevent before – or fix after (i.e. what measures to take).

I'm closing this issue now as I consider it solved. Should you have any questions left, I gladly try answering them if I can of course!

**Comment by aritra-tech** [comment]
Okay got it.
So during the release of v1.0 on GitHub I mistakenly published the APK file not the Signed APK file and on Play Store I have uploaded the Signed app bundle doing all the proper steps required.
So during v1.1.0 I published the generate apk on GitHub and signed app bundle on Play Store.
I don't know how this signing key got changed.
