### ISSUE TITLE
proprietary dependencies

### ISSUE THREAD

**Issue by IzzySoft** [aritra-tech/Notify#54]
Ouch: I didn't mean to be a prophet when I mentioned my scanner, but there we are :cry: The current release comes with a bunch of non-free parts:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeComp,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

6 offenders.
```

That's a bit much for a FOSS app. So may I kindly ask to have at least Crashlytics and Firebase Analytics removed (my guess is the other 4 are just dependencies, and thus will disappear automatically then)? If you need analytics for some reasons, there are [some FOSS alternatives available](https://gitlab.com/-/snippets/1896503#acceptable-analytics).

Until solved, I'll have to add those 3 anti-features to your app now, which in the FOSS and privacy world will look quite scary. Usually, with more than 4 offenders I'd de-list an app – but I trust you will have a solution short-term. :crossed_fingers: I've already quickly checked the pre-release, but that has the same offenders (was to be expected). Again, no hint in the release notes, so it might hit some people unexpectedly and unprepared (no offense meant, just bringing up the "transparency" topic we already discussed – not to put blame but to raise awareness)…

**Comment by aritra-tech** [comment]
Okay let me give some time.
Withing the next release I will fix it up.

**Comment by aritra-tech** [comment]
Can you please check the latest pre-release I have done the required changes

**Comment by IzzySoft** [comment]
Thanks! That looks better already:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

4 offenders.
```

With that fetched (i.e. once it hits my repo), `Tracking` can be dropped. Would be great if we could get rid of the `NonFreeComp` as well, so the app is fully FOSS again. If you didn't add those on purpose we'd have to find out what dragged them in; `gradle :app:dependencies` could help you with that.

**Comment by aritra-tech** [comment]
In the lastest release which will be v1.3.0 beta02, I will be handling this thing.

**Comment by IzzySoft** [comment]
> which is used for push notifications.

I don't know why a note taking app needs push notifications – but if there's a good reason for it, may I recommend using @UnifiedPush instead? Also see the [UnifiedPush](https://unifiedpush.org/) website for details.

**Comment by aritra-tech** [comment]
I am closing this issue I will try to get rid of the `NonFreeComp` in the next release which will be 1.3.0.
Thank you.

**Comment by IzzySoft** [comment]
Thank you for caring! I'd usually ask to keep the issue open until solved (so closing it would send me a reminder) – but as updates are still enabled at my end, my updater will notify me once "offenders" have disappeared. They were set to monthly during the initial issue; I'll set them back to daily now, so the anti-features can be removed as soon as possible. If you'd release a 1.2.x with the changes already done (or I pull the current 1.3.0 beta),`Tracking` could be removed already now. I leave that choice to you :wink:

**Comment by aritra-tech** [comment]
You can take the 1.3.0 beta01.
I will update the required changes in the current version i.e. 1.3.0 soon.

**Comment by IzzySoft** [comment]
OK, pulled the beta manually (without enabling pre-releases per se). The `Tracking` anti-feature is then removed with the next sync around 6 pm UTC.

**Comment by aritra-tech** [comment]
Hey @IzzySoft just wanted to ask that I have already removed all the Firebase dependencies but still Anti-Features are showing up in IzzyOnDroid.

```
Anti-Features:
NonFreeComp (the application includes non-free components):
⇒ The app contains Crashlytics, Firebase Analytics, Firebase, Google Mobile Services.
NonFreeNet (this application promotes/depends a non-Free network service):
⇒ Connections are made to Google servers (Crashlytics, Firebase). 
```

**Comment by IzzySoft** [comment]
Thanks for the heads-up! There are still left-overs (which is why my updater did not alert me to remove the AFs), so I updated the AF description accordingly (effective with the next sync):

![image](https://github.com/aritra-tech/Notify/assets/6781438/b3f32a4e-8c7d-4a3b-ae5a-db6d29efbdde)

**Comment by aritra-tech** [comment]
> Thanks for the heads-up! There are still left-overs (which is why my updater did not alert me to remove the AFs), so I updated the AF description accordingly (effective with the next sync):
> 
> ![image](https://user-images.githubusercontent.com/6781438/273800832-b3f32a4e-8c7d-4a3b-ae5a-db6d29efbdde.png)

Okay got your point.

**Comment by IzzySoft** [comment]
We both had one here, so good you sent the heads-up. At least the anti-feature description is now correct, having the other culprits dropped. Once you removed/replaced Play Core (or both remaining "offenders"), my updater should notify me as one (or both) AFs are dropped (no library remaining for it). If you think you need them for the PlayStore release, you might consider setting up build flavors and offer a `gplay` one with and a `foss` one without them.
