### ISSUE TITLE
Require better screen transition

### ISSUE THREAD

**Issue by pratikksahu** [aritra-tech/Notify#62]
Fade in out transition between screen gives very weird user experience

**Comment by pratikksahu** [comment]
Nav host can be updated to this
NavHost(
            navController = navController,
            startDestination = NotifyScreens.Notes.name,
            modifier = Modifier
                .padding(it),
            enterTransition = {
                slideInVertically(
                    tween(500), initialOffsetY = { -it })
            },
            popEnterTransition = {
                slideInVertically(
                    tween(500), initialOffsetY = { it })
            }
        )

**Comment by aritra-tech** [comment]
> Fade in out transition between screen gives very weird user experience

Yeah your are right.

**Comment by aritra-tech** [comment]
> Nav host can be updated to this `NavHost( navController = navController, startDestination = NotifyScreens.Notes.name, modifier = Modifier .padding(it), enterTransition = { slideInVertically( tween(500), initialOffsetY = { -it }) }, popEnterTransition = { slideInVertically( tween(500), initialOffsetY = { it }) } )`

Can you give some demo video or any resource after implementing this code in BottomNav Bar just wanted to see how it looks.

**Comment by naitgacem** [comment]
@aritra-tech A sample code looks like this:

```kotlin
 setContent {
            val navController = rememberNavController()

            NavHost(
                navController = navController,
                startDestination = Screen.Home.route,
            ) {
                composable(
                    route = Screen.Home.route,
                    enterTransition = { fadeIn() },
                ) {
                    HomeScreen(navController = navController)
                }
```
Check out the [documentation](https://developer.android.com/jetpack/compose/animation/introduction) for more information.
