### ISSUE TITLE
Suggest disallowing main thread queries

### ISSUE THREAD

**Issue by naitgacem** [aritra-tech/Notify#68]
It is meant for developement only and disabling it makes sure no queries are done on the main thread.

**Comment by aritra-tech** [comment]
Can you please explain in detail @naitgacem.

**Comment by logickoder** [comment]
I think he's talking about room queries

**Comment by naitgacem** [comment]
@aritra-tech sorry for the vague note, yes as @logickoder said i was referring to Room database instantiation with the `.allowMainThreadQueries` method.

**Comment by aritra-tech** [comment]
Ohh okay got your point actually I have added it because there was some error coming up related to Room so after searching for the solution I got that, and yeah it's better to remove it I guess.

**Comment by aritra-tech** [comment]
Fixed it @naitgacem .
