### ISSUE TITLE
User can pick multiple images. 

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#72]
Now during the time of adding the notes user can only add one image but it's better if we give the users access to add multiple images at a time and during the time of editing the notes if the user wants they can add more images from their gallery.

**Comment by binayshaw7777** [comment]
I want to do this.

**Comment by aritra-tech** [comment]
Sure @binayshaw7777.
All the best

**Comment by aritra-tech** [comment]
Hey @binayshaw7777 any updates?

**Comment by beradeep** [comment]
Hey @aritra-tech, I would like to work on this.

**Comment by aritra-tech** [comment]
Sure @beradeep

**Comment by beradeep** [comment]
Hey @aritra-tech updated it.
