### ISSUE TITLE
Anti-features and bad permissions (improvement)

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#79]
A 100% offline app doesn't need for internet permission.

![1000041843](https://github.com/aritra-tech/Notify/assets/113377431/75e07085-e3ac-46cf-a156-ead02f1dd6e5)

**Comment by aritra-tech** [comment]
Thanks for noticing it.

**Comment by aritra-tech** [comment]
Ohh my bad.
Thanks for pointing it out

**Comment by aritra-tech** [comment]
The updated release solves this issue.
Thanks for pointing it out @serrq.
I'm closing this issue.

**Comment by aritra-tech** [comment]
Okay will look into it I don't know why it's coming up till now.

**Comment by aritra-tech** [comment]
If you want you can donate to me on GitHub only.

**Comment by aritra-tech** [comment]
Sorry @serrq but I also don't like crypto and all no worries.
Thanks for your support.

**Comment by aritra-tech** [comment]
Thank you @serrq for your support.
Means a lot.
