### ISSUE TITLE
[E] [F] Interoperability with Quillnote (backup/restore)

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#80]
Backup/restore compatibility with Quillnote standard (open source).

https://github.com/msoultanidis/quillnote

**Comment by aritra-tech** [comment]
Can you please explain in detail @serrq

**Comment by aritra-tech** [comment]
Okay got your point.
I will be fixing this "permissions and anti-features" issue soon.
And thanks for liking Notify.

**Comment by aritra-tech** [comment]
Got your point.
