### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#81]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR addresses available for donations (addresses have to be copyable).

Here two apps, as donate integration examples.

![1000040555](https://github.com/aritra-tech/Notify/assets/113377431/78f63f73-0535-4535-88d5-0658016e41d3)

![1000040544](https://github.com/aritra-tech/Notify/assets/113377431/1adfa9fb-c01b-4e06-bb2a-8f053c631eca)

**Comment by aritra-tech** [comment]
Okay, @serrq will look into it in the next release.
Thank you.
