### ISSUE TITLE
Create a Reminder section

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#84]

**Comment by javaman97** [comment]
@aritra-tech I would love to work on this issue, would you please assign me this issue?

**Comment by aritra-tech** [comment]
Sure @javaman97 
All the best

**Comment by javaman97** [comment]
@aritra-tech Would you please explain it in more detail, In this Reminder section I need to add a timer and anything else.

**Comment by aritra-tech** [comment]
It will be simply a reminder/to-do app.
If you have used Google Keep Notes then you will find the remainder section same like that only.

**Comment by aritra-tech** [comment]
Any update @javaman97?

**Comment by salmanA169** [comment]
assign me 
I will do that after I finish my issue #176

**Comment by aritra-tech** [comment]
Let's wait for 2 more days after that I will assign you.

**Comment by aritra-tech** [comment]
Hey @salmanA169 are you willing to do this issue?

**Comment by salmanA169** [comment]
Yes

**Comment by aritra-tech** [comment]
Okay, then I'm assigning this to you.
All the best

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/ef246769-637f-41de-af57-5ebf0943c104


not finish yet 
I just start now

**Comment by aritra-tech** [comment]
Looking nice
But I was also thinking of creating another section of the Reminder section. Means there will be another section of Reminder in Bottom Navigation Bar

**Comment by salmanA169** [comment]
I think no need create new reminder screen
It's enough add reminder in note screen like Google keep

**Comment by aritra-tech** [comment]
So how can the user be able to understand which one is his reminder or note?

**Comment by salmanA169** [comment]
![Screenshot_20231022_164218_Keep Notes.jpg](https://github.com/aritra-tech/Notify/assets/40442174/497f0f92-1cb0-4839-bab8-92f05c1c56fc)

I will add this on note card like this

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/46580a23-b89c-476f-acec-2e861b8f4ee4

sorry for late 
because I have work I am so busy and also I am student I have exams 

Anyway I almost finish it 
just remining schedule alarm manager

**Comment by aritra-tech** [comment]
Can we put the reminder one below the character and words text field @salmanA169?
It will look better

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/9e281c18-7efa-464b-a56f-5a62741c8219

I just finished Implemented alarm manager 
to perfect schedule specific date time it works fine  just remining improve notification title and content I am not finished yet

**Comment by aritra-tech** [comment]
Nice work @salmanA169

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/467a5085-5b36-488e-b0ea-574e81fcdd83

it works fine for now
I am currently testing after that I will create new PR

**Comment by aritra-tech** [comment]
LGTM
Just a question
Can we also edit the reminder if we want.

**Comment by salmanA169** [comment]
no 
but I can do that if you want

**Comment by aritra-tech** [comment]
Yeah please if the user gives the wrong time and saves it and wants to change it then he can't so it's better to give the function of edit of reminder if he/she wants.

**Comment by salmanA169** [comment]
https://github.com/aritra-tech/Notify/assets/40442174/2ceea6ef-1b05-4aaf-9427-b6458963d56e

now you can now edit reminder after create new one and also when move note to trash it will cancel alarm
also when restore note it will reschedule new alarm I think it work fine now

**Comment by aritra-tech** [comment]
> bandicam.2023-10-28.20-58-31-387.mp4 
> now you can now edit reminder after create new one and also when move note to trash it will cancel alarm also when restore note it will reschedule new alarm I think it work fine now

Nice work @salmanA169
