### ISSUE TITLE
Implement Camera X for taking pictures

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Notify#86]
So the user can click images using their camera and add them along with their Notes.
They can also add multiple images using their camera.

**Comment by poseidon2060** [comment]
hey @aritra-tech can I work on this issue?

**Comment by aritra-tech** [comment]
Sure @poseidon2060.
All the best.

**Comment by poseidon2060** [comment]
Thankyou, please assign me this issue😇

**Comment by aritra-tech** [comment]
Any update @poseidon2060?

**Comment by aritra-tech** [comment]
Right now only thought of the image, yeah your point is valid we can do it will add it to the bucket list, and will work on it.

**Comment by poseidon2060** [comment]
@aritra-tech I am sorry I got some other work and am unable to work on this issue right now, hence I am unassigning myself from the issue
Apologies for the inconveniece

**Comment by Ismail-AD** [comment]
@aritra-tech  I'd like to work on this issue. Could you please assign it to me?

**Comment by aritra-tech** [comment]
Yeah sure @Ismail-AD 
All the best

**Comment by Ismail-AD** [comment]
@aritra-tech check out PR bro

**Comment by aritra-tech** [comment]
> @aritra-tech check out PR bro

Yeah, seen that you have raised the PR will review it by tomorrow and merge it.
Thanks for the contribution
