### ISSUE TITLE
Status Bar not visible

### ISSUE THREAD

**Issue by bhoomi0104** [aritra-tech/Notify#88]
In the light mode, the status bar is white and the text in the status bar is also white, and due to that, it is not visible. While in the dark mode, the status bar is black, and the text inside it is white so it is visible. The problem is in light mode only.

**Comment by aritra-tech** [comment]
Thanks for noticing it @bhoomi0104.
If you want to work on it you can.

**Comment by bhoomi0104** [comment]
Yes I am working on it
