### ISSUE TITLE
[B] The text does not fit the top position of the keyboard, so I cannot see what I am editing

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#91]
Notify 1.3.1 (fdroid)
OnePlus CPH2399
Android 13

![1000041972](https://github.com/aritra-tech/Notify/assets/113377431/79033c79-edde-455f-9417-5aa986af164a)

![1000041974](https://github.com/aritra-tech/Notify/assets/113377431/d0ac1657-9a1a-43f2-b707-992b314737ca)

**Comment by aritra-tech** [comment]
Thanks @serrq for pointing it out will be fixing it in the next update.

**Comment by Devendra34** [comment]
Hi @aritra-tech,
Can I try for this issue?

**Comment by aritra-tech** [comment]
Sure @Devendra34 
All the best

**Comment by aritra-tech** [comment]
Any update @Devendra34?

**Comment by Devendra34** [comment]
Hi @aritra-tech,
In XML when we have EditText inside a ScrollView, we get our desired auto scroll experience properly..
The same when we try in compose with TextField inside Scrollable Column, it is not supported by default.

I searched and experimented various ways to solve this issue, but I was not getting a satisfactory result till yesterday.
Recently I found one possible solution, which I'll try to push today. Will document the selected approach in PR description as well.

You can expect a PR by EOD.

**Comment by aritra-tech** [comment]
Okay got your point.
You can refer to these two articles
- [Keyboard handling in Jetpack Compose](https://dev.to/tkuenneth/keyboard-handling-in-jetpack-compose-2593)
- [Keyboard Handling In Jetpack Compose — All You Need To Know](https://blog.canopas.com/keyboard-handling-in-jetpack-compose-all-you-need-to-know-3e6fddd30d9a)

**Comment by Devendra34** [comment]
Hi @aritra-tech,
Here's my latest update:
[Screen_recording_20231005_115541.webm](https://github.com/aritra-tech/Notify/assets/51832211/c7e4557b-5118-4b67-bbeb-c7ed9d72c3b9)


As seen in the demo video, the experience is better due to auto scroll to current cursor position
I will rebase and push the stable code

**Comment by aritra-tech** [comment]
> Hi @aritra-tech,
> Here's my latest update:
> 
> ![Screen_recording_20231005_115541](https://github.com/aritra-tech/Notify/assets/51832211/079c490a-019f-45f1-a906-25c248a07e72)
> 
> As seen in the demo video, the experience is better due to auto scroll to current cursor position
> I will rebase and push the stable code
> 
> 

Nice work @Devendra34

**Comment by aritra-tech** [comment]
Hey @Devendra34 any update?
Just asking because I will be releasing the latest version tomorrow so wanted this issue to be fixed.

**Comment by Devendra34** [comment]
Hi @aritra-tech,
Apologies for the delay, it was a super tight week!
I have raised #123, you may go through it

**Comment by aritra-tech** [comment]
> Hi @aritra-tech, Apologies for the delay, it was a super tight week! I have raised #123, you may go through it

No issues bro.
