### ISSUE TITLE
[P] Protection against "recent apps" and "screenshot"

### ISSUE THREAD

**Issue by serrq** [aritra-tech/Notify#97]
Some apps give the ability (optional) to switch ON/OFF the "screenshot" and "recent apps" protection feature by other prying apps.
Basically a privacy feature. Here an implementation and some examples.

![1000041990](https://github.com/aritra-tech/Notify/assets/113377431/2e7d379a-c81c-41b1-88d2-7170fc429af7)

**Comment by aritra-tech** [comment]
Okay will look into it.

**Comment by beradeep** [comment]
Hey @aritra-tech, I would like to work on this.

**Comment by aritra-tech** [comment]
Sure @beradeep
