### ISSUE TITLE
Biometric feature crashes the app

### ISSUE THREAD

**Issue by preetishsrivastav** [aritra-tech/Notify#98]
**Bug**

When we open the settings of the app and click on biometric the app get crashed.

Device OPPO
Android 8.1

https://github.com/aritra-tech/Notify/assets/87092955/69d7b093-ec22-4aca-99d8-34143921c587

**Comment by aritra-tech** [comment]
Can you check the `logcat` once and tell me what is coming up?

**Comment by preetishsrivastav** [comment]
Yeah sure

**Comment by aritra-tech** [comment]
Hey @preetishsrivastav any update?
