### ISSUE TITLE
Add Feature : Multi-selection for deleting notes

### ISSUE THREAD

**Issue by bhoomi0104** [aritra-tech/Notify#99]
Currently, users must open a note to delete it. This can be complex, especially if users have a large number of notes. A swipe to delete feature would allow users to delete notes from the home screen with a single gesture, making it much easier and faster to manage their notes.

**Comment by aritra-tech** [comment]
How will the user know that he/she can delete the notes by swiping them?
Actually, this feature was already present but I removed it because the user doesn't know that they can delete the note by swiping.

**Comment by aritra-tech** [comment]
If you have any other idea you can share with me

**Comment by bhoomi0104** [comment]
You can provide a tooltip for that. I have seen in many apps that when a user opens the app for the first time, the app will guide them about the features. You can also do that.

**Comment by aritra-tech** [comment]
> You can provide a tooltip for that. I have seen in many apps that when a user opens the app for the first time, the app will guide them about the features. You can also do that. Let me know your thought on this

Ig tooltip is not a great option, tooltip looks better for some complex app and i don't think that we can present the user that we have a swipe to delete option.

**Comment by aritra-tech** [comment]
> I would like a batch delete mode (multiple actions at once).
> 
> For example I could delete 10 boxes at time.

That is what I was thinking about @bhoomi0104, means user can select multiple notes at a time and then we can delete all that notes.

**Comment by aritra-tech** [comment]
> > How will the user know that he/she can delete the notes by swiping them? Actually, this feature was already present but I removed it because the user doesn't know that they can delete the note by swiping.
> 
> Introduce a "What's new" section.
> 
> ![1000042005](https://user-images.githubusercontent.com/113377431/271832801-048320c7-60a9-47dd-8eec-d940fdaa2bd9.jpg)
> 
> ![1000042007](https://user-images.githubusercontent.com/113377431/271832804-d891a31a-b058-42f9-9001-0d94d6707afc.jpg)

Yeah we can do that 
Thanks for the idea @serrq

**Comment by bhoomi0104** [comment]
> > I would like a batch delete mode (multiple actions at once).
> > For example I could delete 10 boxes at time.
> 
> That is what I was thinking about @bhoomi0104, means user can select multiple notes at a time and then we can delete all that notes.

Yes we can do that. It would be better.

**Comment by bhoomi0104** [comment]
> "Swipe to delete" will have the UNDO action? Until 5 seconds I can cancel the action easily. Basically a countdown.

Yes it is also a good option but I think the multiple notes selection and delete them is better. because in the grid, it is not possible to add swipe to delete option

**Comment by aritra-tech** [comment]
Yeah right.
If you want to do this feature go ahead @bhoomi0104

**Comment by bhoomi0104** [comment]
Yes I will work on this

**Comment by aritra-tech** [comment]
Okay 
All the best.

**Comment by aritra-tech** [comment]
Any update @bhoomi0104?

**Comment by bhoomi0104** [comment]
Yes working on it.
![Screenshot_20231006-145506](https://github.com/aritra-tech/Notify/assets/20904033/cffd4502-3d37-4020-be4c-88c8c94a57e5)

**Comment by aritra-tech** [comment]
Ohh nice 🙌.
All the best, if you are stuck in any place please ping me.

**Comment by bhoomi0104** [comment]
How can I show snackbar below floating button? @aritra-tech

![Screenshot_20231006-214530](https://github.com/aritra-tech/Notify/assets/20904033/83e010fe-3ac9-430d-8b69-e37b9d95c3d6)

**Comment by aritra-tech** [comment]
> How can I show snackbar below floating button? @aritra-tech
> 
> ![Screenshot_20231006-214530](https://user-images.githubusercontent.com/20904033/273273269-83e010fe-3ac9-430d-8b69-e37b9d95c3d6.jpg)

When we are triggering snack-bar at that moment can we hide the FAB?

**Comment by aritra-tech** [comment]
Take a look into it @bhoomi0104 if it helps - https://github.com/flutter/flutter/issues/123541

**Comment by bhoomi0104** [comment]
As per the official guidelines "Snackbars should appear above FABs."

**Comment by bhoomi0104** [comment]
What should we do?

**Comment by aritra-tech** [comment]
> As per the official guidelines "Snackbars should appear above FABs."

Yeah right
